fragment PostParts on Post {
  __typename
  title
  description
  heroImage
  draft
  category
  pubDate
  updateDate
  tags
  SButton
}

fragment ProjectParts on Project {
  __typename
  title
  description
  image
  imageUrl
  demo
  repository
  technologies
  draft
  featured
  order
  date
  company
  client
  role
  status
  private
  category
  badges
}
