import js from '@eslint/js'
import astro from 'eslint-plugin-astro'
import tseslint from '@typescript-eslint/eslint-plugin'
import tsParser from '@typescript-eslint/parser'
import prettierConfig from 'eslint-config-prettier'
import globals from 'globals'

export default [
	{
		// tina/__generated__ is autogenerated by `tinacms build`, never hand-edited
		ignores: ['dist/**', 'node_modules/**', '.vercel/**', 'admin/**', '.astro/**', 'tina/__generated__/**']
	},
	js.configs.recommended,
	...astro.configs['flat/recommended'],
	...astro.configs['flat/jsx-a11y-recommended'],
	{
		files: ['**/*.{ts,tsx}'],
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				project: './tsconfig.json'
			},
			globals: {
				...globals.browser,
				...globals.node
			}
		},
		plugins: {
			'@typescript-eslint': tseslint
		},
		rules: {
			...tseslint.configs.recommended.rules,
			// Astro generates /// <reference path="../.astro/types.d.ts" /> in env.d.ts --
			// an ambient .d.ts reference with no import-style equivalent, so path stays allowed.
			'@typescript-eslint/triple-slash-reference': [
				'error',
				{ path: 'always', types: 'prefer-import', lib: 'always' }
			]
		}
	},
	{
		files: ['**/*.{js,mjs,cjs}'],
		languageOptions: {
			globals: {
				...globals.browser,
				...globals.node
			}
		}
	},
	prettierConfig
]
