import {
  GITHUB_USERNAME,
  GITHUB_TOKEN,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
} from "astro:env/server";

export { GITHUB_USERNAME, GITHUB_TOKEN, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET };

export const MAX_POSTS = 5 
